name: Lunar release

on:
  push:
    tags:
      - 'lunar*'

jobs:
  release:
    runs-on: ubuntu-latest
    container: ulauncher/build-image:5.0
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Launchpad
        env:
          LAUNCHPAD_SSH_TAR: ${{ secrets.LAUNCHPAD_SSH_TAR }}
          LAUNCHPAD_PUB_KEY: ${{ secrets.LAUNCHPAD_PUB_KEY }}
          LAUNCHPAD_SECRET_KEY: ${{ secrets.LAUNCHPAD_SECRET_KEY }}
          PPA: agornostal/ulauncher
        run: |
          echo "PPA: $PPA"
          echo -n "$LAUNCHPAD_SSH_TAR" | base64 -d > scripts/launchpad.ssh.tar
          echo -n "$LAUNCHPAD_PUB_KEY" | base64 -d > scripts/launchpad-public.key
          echo -n "$LAUNCHPAD_SECRET_KEY" | base64 -d > scripts/launchpad-secret.key
          tar -xvf scripts/launchpad.ssh.tar -C /
          RELEASE=lunar ./ul build-deb 5.15.2 --upload
