name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate
        if: ${{ env.GITHUB_REF_TYPE != 'tag' }}
        run: |
          echo "Ref must be a tag"
          exit 1

      - name: Upload release to Launchpad
        env:
          LAUNCHPAD_SSH_TAR: ${{ secrets.LAUNCHPAD_SSH_TAR }}
          LAUNCHPAD_PUB_KEY: ${{ secrets.LAUNCHPAD_PUB_KEY }}
          LAUNCHPAD_SECRET_KEY: ${{ secrets.LAUNCHPAD_SECRET_KEY }}
        run: |
          source ./scripts/common.sh
          docker pull $BUILD_IMAGE
          echo -n "$LAUNCHPAD_SSH_TAR" | base64 -d > scripts/launchpad.ssh.tar
          echo -n "$LAUNCHPAD_PUB_KEY" | base64 -d > scripts/launchpad-public.key
          echo -n "$LAUNCHPAD_SECRET_KEY" | base64 -d > scripts/launchpad-secret.key
          ./ul upload-release $GITHUB_REF_NAME
