name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Ref from workflow: $GITHUB_REF_NAME"
          GIT_VERSION=$(git describe --tags --dirty)
          echo "Tag from git: $GIT_VERSION"
#          source ./scripts/common.sh
#          docker pull $BUILD_IMAGE
#
#      - name: Upload release to Launchpad
#        env:
#          LAUNCHPAD_SSH_TAR: ${{ secrets.LAUNCHPAD_SSH_TAR }}
#          LAUNCHPAD_PUB_KEY: ${{ secrets.LAUNCHPAD_PUB_KEY }}
#          LAUNCHPAD_SECRET_KEY: ${{ secrets.LAUNCHPAD_SECRET_KEY }}
#        run: |
#          echo -n "$LAUNCHPAD_SSH_TAR" | base64 -d > scripts/launchpad.ssh.tar
#          echo -n "$LAUNCHPAD_PUB_KEY" | base64 -d > scripts/launchpad-public.key
#          echo -n "$LAUNCHPAD_SECRET_KEY" | base64 -d > scripts/launchpad-secret.key
#          ./ul upload-release $GITHUB_REF_NAME
