name: Release

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release
        run: |
          echo "Tag is created: $GITHUB_REF_NAME"

      # - name: Upload release assets
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: |
      #       ulauncher_${{ github.ref }}.tar.gz
      #       ulauncher_${{ github.ref }}_all.deb
      #     asset_name: |
      #       ulauncher_${{ github.ref }}.tar.gz
      #       ulauncher_${{ github.ref }}_all.deb
      #     asset_content_type: application/gzip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Call after_deploy script
      #   env:
      #     TRAVIS_TAG: ${{ github.ref }}
      #   run: |
      #     ./ul upload-release $TRAVIS_TAG
