name: Tests

on:
  pull_request:
    branches:
      - v5
      - v6
  push:
    branches:
      - '*'
  create:
    tags:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tests
        run: |
          source ./scripts/common.sh
          docker pull $BUILD_IMAGE
          ./ul run-ci
